# Generated by Django 5.0.4 on 2024-06-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_view',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
