# Generated by Django 5.0.4 on 2024-06-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_gallery_view_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
