# Generated by Django 5.0.4 on 2024-06-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mail',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
