# Generated by Django 5.0.4 on 2024-06-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mail',
        ),
    ]
