# Generated by Django 5.0.4 on 2024-06-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_cart_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
