# Generated by Django 5.0.4 on 2024-06-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_orderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='qty',
            new_name='quantity',
        ),
    ]
