# Generated by Django 5.0.4 on 2024-06-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_rename_qty_orderdetail_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
    ]
