# Generated by Django 5.0.4 on 2024-06-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_paymentprocess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='paymentProcess',
        ),
    ]
