# Generated by Django 5.0.4 on 2024-11-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_paymentcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcart',
            name='name',
        ),
    ]
